### ISSUE TITLE
Error voor Features

### ISSUE THREAD

**Issue by eggied97** [Thandruil/qwirkle#2]
Moeten we ook een Error returnen als er met het identify'en een onbekende Feature wordt meegestuurt? want hier is nog geen dedicated error code voor volgensmij

**Comment by erikgaal** [comment]
Hey Egbert,

Kort gezegd, nee. Het zou namelijk kunnen dat ik als groepje een compleet nieuwe feature implementeer en deze wil gebruiken op een x aantal servers. Zolang die dat geïmplementeerd hebben mogen ze meedoen, maar anders gewoon negeren. De features die je dus wilt gebruiken aan beide kanten, is de union van de features van beide kanten.

Voorbeeld:
**Client** heeft CHAT,LOBBY
**Server** heeft CHAT,LEADERBOARD
Dan is het resultaat dat ze alleen CHAT als extra functie gebruiken.
