### ISSUE TITLE
IProtocol ServerQueueOk

### ISSUE THREAD

**Issue by eggied97** [Thandruil/qwirkle#6]
Wat wordt er bedoelt met de parameter 'list of number of players'?
Is dit het aantal van players in de queues (in de volgorde dat je ze gejoined hebt?), of is dit bedoelt als conformatie dat je de gegeven queues hebt gequeued?

**Comment by erikgaal** [comment]
SERVER_QUEUE word na de CLIENT_QUEUE gestuurd zodat de cliënt weet aan
welke Queues die is toegevoegd. Als ik als cliënt wil queuen voor 2,4 dan
controleert de server dit (en dit mag) en stuurt naar de cliënt OK 2,4

Op ma 25 jan. 2016 10:12 schreef Egbert Dijkstra (eggied97) <
notifications@github.com>:
